[2025-01-15T12:55:40.272+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ETL_influencer_marchendise.data_load manual__2025-01-15T12:55:23.413181+00:00 [queued]>
[2025-01-15T12:55:40.278+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ETL_influencer_marchendise.data_load manual__2025-01-15T12:55:23.413181+00:00 [queued]>
[2025-01-15T12:55:40.279+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-01-15T12:55:40.279+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2025-01-15T12:55:40.279+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-01-15T12:55:40.285+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): data_load> on 2025-01-15 12:55:23.413181+00:00
[2025-01-15T12:55:40.288+0000] {standard_task_runner.py:52} INFO - Started process 613 to run task
[2025-01-15T12:55:40.290+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_influencer_marchendise', 'data_load', 'manual__2025-01-15T12:55:23.413181+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/AirflowM3.py', '--cfg-path', '/tmp/tmpidkcxmup', '--error-file', '/tmp/tmp86jx6u1h']
[2025-01-15T12:55:40.291+0000] {standard_task_runner.py:80} INFO - Job 4: Subtask data_load
[2025-01-15T12:55:40.324+0000] {task_command.py:371} INFO - Running <TaskInstance: ETL_influencer_marchendise.data_load manual__2025-01-15T12:55:23.413181+00:00 [running]> on host 85e61d7672fe
[2025-01-15T12:55:40.366+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=afif
AIRFLOW_CTX_DAG_ID=ETL_influencer_marchendise
AIRFLOW_CTX_TASK_ID=data_load
AIRFLOW_CTX_EXECUTION_DATE=2025-01-15T12:55:23.413181+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-01-15T12:55:23.413181+00:00
[2025-01-15T12:55:40.369+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-01-15T12:55:40.369+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'sudo -u *** python /opt/***/dags/load.py']
[2025-01-15T12:55:40.375+0000] {subprocess.py:85} INFO - Output:
[2025-01-15T12:55:40.408+0000] {subprocess.py:92} INFO -   File "/opt/***/dags/load.py", line 39
[2025-01-15T12:55:40.408+0000] {subprocess.py:92} INFO -     print(f'Inserted {len(data)} records into {'p2m3'}.{'etl_pipeline'}')
[2025-01-15T12:55:40.408+0000] {subprocess.py:92} INFO -                                                    ^
[2025-01-15T12:55:40.408+0000] {subprocess.py:92} INFO - SyntaxError: invalid syntax
[2025-01-15T12:55:40.410+0000] {subprocess.py:96} INFO - Command exited with return code 1
[2025-01-15T12:55:40.419+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-15T12:55:40.421+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_influencer_marchendise, task_id=data_load, execution_date=20250115T125523, start_date=20250115T125540, end_date=20250115T125540
[2025-01-15T12:55:40.427+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 4 for task data_load (Bash command failed. The command returned a non-zero exit code 1.; 613)
[2025-01-15T12:55:40.430+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-01-15T12:55:40.447+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
