[2025-01-15T12:59:11.850+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ETL_influencer_marchendise.data_load manual__2025-01-15T12:58:57.029697+00:00 [queued]>
[2025-01-15T12:59:11.862+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ETL_influencer_marchendise.data_load manual__2025-01-15T12:58:57.029697+00:00 [queued]>
[2025-01-15T12:59:11.863+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-01-15T12:59:11.863+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2025-01-15T12:59:11.863+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-01-15T12:59:11.871+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): data_load> on 2025-01-15 12:58:57.029697+00:00
[2025-01-15T12:59:11.877+0000] {standard_task_runner.py:52} INFO - Started process 1098 to run task
[2025-01-15T12:59:11.879+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_influencer_marchendise', 'data_load', 'manual__2025-01-15T12:58:57.029697+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/AirflowM3.py', '--cfg-path', '/tmp/tmpr1bmzdx6', '--error-file', '/tmp/tmp1r5a_k1p']
[2025-01-15T12:59:11.880+0000] {standard_task_runner.py:80} INFO - Job 7: Subtask data_load
[2025-01-15T12:59:11.928+0000] {task_command.py:371} INFO - Running <TaskInstance: ETL_influencer_marchendise.data_load manual__2025-01-15T12:58:57.029697+00:00 [running]> on host 85e61d7672fe
[2025-01-15T12:59:11.974+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=afif
AIRFLOW_CTX_DAG_ID=ETL_influencer_marchendise
AIRFLOW_CTX_TASK_ID=data_load
AIRFLOW_CTX_EXECUTION_DATE=2025-01-15T12:58:57.029697+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-01-15T12:58:57.029697+00:00
[2025-01-15T12:59:11.976+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-01-15T12:59:11.977+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'sudo -u *** python /opt/***/dags/load.py']
[2025-01-15T12:59:11.983+0000] {subprocess.py:85} INFO - Output:
[2025-01-15T12:59:12.015+0000] {subprocess.py:92} INFO -   File "/opt/***/dags/load.py", line 39
[2025-01-15T12:59:12.016+0000] {subprocess.py:92} INFO -     print(f'Inserted {len(data)} records into {'p2m3'}.{'etl_pipeline'}')
[2025-01-15T12:59:12.016+0000] {subprocess.py:92} INFO -                                                    ^
[2025-01-15T12:59:12.016+0000] {subprocess.py:92} INFO - SyntaxError: invalid syntax
[2025-01-15T12:59:12.017+0000] {subprocess.py:96} INFO - Command exited with return code 1
[2025-01-15T12:59:12.027+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-15T12:59:12.032+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_influencer_marchendise, task_id=data_load, execution_date=20250115T125857, start_date=20250115T125911, end_date=20250115T125912
[2025-01-15T12:59:12.041+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 7 for task data_load (Bash command failed. The command returned a non-zero exit code 1.; 1098)
[2025-01-15T12:59:12.058+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-01-15T12:59:12.077+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
