[2025-01-14T04:11:13.019+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ETL_influencer_marchendise.data_extract manual__2025-01-14T04:01:34.458324+00:00 [queued]>
[2025-01-14T04:11:13.024+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ETL_influencer_marchendise.data_extract manual__2025-01-14T04:01:34.458324+00:00 [queued]>
[2025-01-14T04:11:13.024+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-01-14T04:11:13.024+0000] {taskinstance.py:1369} INFO - Starting attempt 4 of 5
[2025-01-14T04:11:13.024+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-01-14T04:11:13.030+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): data_extract> on 2025-01-14 04:01:34.458324+00:00
[2025-01-14T04:11:13.033+0000] {standard_task_runner.py:52} INFO - Started process 545 to run task
[2025-01-14T04:11:13.034+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_influencer_marchendise', 'data_extract', 'manual__2025-01-14T04:01:34.458324+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/AirflowM3.py', '--cfg-path', '/tmp/tmpdc7olr77', '--error-file', '/tmp/tmpqe99jor2']
[2025-01-14T04:11:13.035+0000] {standard_task_runner.py:80} INFO - Job 5: Subtask data_extract
[2025-01-14T04:11:13.065+0000] {task_command.py:371} INFO - Running <TaskInstance: ETL_influencer_marchendise.data_extract manual__2025-01-14T04:01:34.458324+00:00 [running]> on host b11c54afad7a
[2025-01-14T04:11:13.099+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=afif
AIRFLOW_CTX_DAG_ID=ETL_influencer_marchendise
AIRFLOW_CTX_TASK_ID=data_extract
AIRFLOW_CTX_EXECUTION_DATE=2025-01-14T04:01:34.458324+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-01-14T04:01:34.458324+00:00
[2025-01-14T04:11:13.100+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-01-14T04:11:13.101+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***-with-spark/dags/extract.py']
[2025-01-14T04:11:13.104+0000] {subprocess.py:85} INFO - Output:
[2025-01-14T04:11:13.115+0000] {subprocess.py:92} INFO - python: can't open file '/opt/***-with-spark/dags/extract.py': [Errno 2] No such file or directory
[2025-01-14T04:11:13.116+0000] {subprocess.py:96} INFO - Command exited with return code 2
[2025-01-14T04:11:13.124+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-01-14T04:11:13.126+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_influencer_marchendise, task_id=data_extract, execution_date=20250114T040134, start_date=20250114T041113, end_date=20250114T041113
[2025-01-14T04:11:13.132+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 5 for task data_extract (Bash command failed. The command returned a non-zero exit code 2.; 545)
[2025-01-14T04:11:13.176+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-01-14T04:11:13.199+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
