[2025-01-14T04:04:20.195+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ETL_influencer_marchendise.data_extract manual__2025-01-14T04:01:34.458324+00:00 [queued]>
[2025-01-14T04:04:20.200+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ETL_influencer_marchendise.data_extract manual__2025-01-14T04:01:34.458324+00:00 [queued]>
[2025-01-14T04:04:20.200+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-01-14T04:04:20.200+0000] {taskinstance.py:1369} INFO - Starting attempt 3 of 4
[2025-01-14T04:04:20.200+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-01-14T04:04:20.206+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): data_extract> on 2025-01-14 04:01:34.458324+00:00
[2025-01-14T04:04:20.209+0000] {standard_task_runner.py:52} INFO - Started process 332 to run task
[2025-01-14T04:04:20.210+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_influencer_marchendise', 'data_extract', 'manual__2025-01-14T04:01:34.458324+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/AirflowM3.py', '--cfg-path', '/tmp/tmpndi5xl5x', '--error-file', '/tmp/tmp1dx04nqc']
[2025-01-14T04:04:20.211+0000] {standard_task_runner.py:80} INFO - Job 4: Subtask data_extract
[2025-01-14T04:04:20.242+0000] {task_command.py:371} INFO - Running <TaskInstance: ETL_influencer_marchendise.data_extract manual__2025-01-14T04:01:34.458324+00:00 [running]> on host b11c54afad7a
[2025-01-14T04:04:20.276+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=afif
AIRFLOW_CTX_DAG_ID=ETL_influencer_marchendise
AIRFLOW_CTX_TASK_ID=data_extract
AIRFLOW_CTX_EXECUTION_DATE=2025-01-14T04:01:34.458324+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-01-14T04:01:34.458324+00:00
[2025-01-14T04:04:20.276+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-01-14T04:04:20.277+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'python /users/afifmakruf/dekstop/hacktiv8/rmt-002/repo/***-with-spark/dags/extract.py']
[2025-01-14T04:04:20.281+0000] {subprocess.py:85} INFO - Output:
[2025-01-14T04:04:20.292+0000] {subprocess.py:92} INFO - python: can't open file '/users/afifmakruf/dekstop/hacktiv8/rmt-002/repo/***-with-spark/dags/extract.py': [Errno 2] No such file or directory
[2025-01-14T04:04:20.293+0000] {subprocess.py:96} INFO - Command exited with return code 2
[2025-01-14T04:04:20.300+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-01-14T04:04:20.302+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_influencer_marchendise, task_id=data_extract, execution_date=20250114T040134, start_date=20250114T040420, end_date=20250114T040420
[2025-01-14T04:04:20.307+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 4 for task data_extract (Bash command failed. The command returned a non-zero exit code 2.; 332)
[2025-01-14T04:04:20.311+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-01-14T04:04:20.326+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
