[2025-01-14T04:20:05.532+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ETL_influencer_marchendise.data_extract manual__2025-01-14T04:01:34.458324+00:00 [queued]>
[2025-01-14T04:20:05.537+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ETL_influencer_marchendise.data_extract manual__2025-01-14T04:01:34.458324+00:00 [queued]>
[2025-01-14T04:20:05.537+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-01-14T04:20:05.537+0000] {taskinstance.py:1369} INFO - Starting attempt 7 of 8
[2025-01-14T04:20:05.537+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-01-14T04:20:05.543+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): data_extract> on 2025-01-14 04:01:34.458324+00:00
[2025-01-14T04:20:05.545+0000] {standard_task_runner.py:52} INFO - Started process 843 to run task
[2025-01-14T04:20:05.547+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_influencer_marchendise', 'data_extract', 'manual__2025-01-14T04:01:34.458324+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/AirflowM3.py', '--cfg-path', '/tmp/tmp9q2s4j49', '--error-file', '/tmp/tmp8oqsu1hn']
[2025-01-14T04:20:05.548+0000] {standard_task_runner.py:80} INFO - Job 8: Subtask data_extract
[2025-01-14T04:20:05.576+0000] {task_command.py:371} INFO - Running <TaskInstance: ETL_influencer_marchendise.data_extract manual__2025-01-14T04:01:34.458324+00:00 [running]> on host b11c54afad7a
[2025-01-14T04:20:05.609+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=afif
AIRFLOW_CTX_DAG_ID=ETL_influencer_marchendise
AIRFLOW_CTX_TASK_ID=data_extract
AIRFLOW_CTX_EXECUTION_DATE=2025-01-14T04:01:34.458324+00:00
AIRFLOW_CTX_TRY_NUMBER=7
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-01-14T04:01:34.458324+00:00
[2025-01-14T04:20:05.610+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-01-14T04:20:05.610+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags//extract.py']
[2025-01-14T04:20:05.614+0000] {subprocess.py:85} INFO - Output:
[2025-01-14T04:20:05.722+0000] {subprocess.py:92} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/spark-class: line 71: /usr/lib/jvm/java-11-openjdk-amd64/bin/java: No such file or directory
[2025-01-14T04:20:05.722+0000] {subprocess.py:92} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/spark-class: line 96: CMD: bad array subscript
[2025-01-14T04:20:05.823+0000] {subprocess.py:92} INFO - Traceback (most recent call last):
[2025-01-14T04:20:05.824+0000] {subprocess.py:92} INFO -   File "/opt/***/dags//extract.py", line 41, in <module>
[2025-01-14T04:20:05.824+0000] {subprocess.py:92} INFO -     extract(path)
[2025-01-14T04:20:05.824+0000] {subprocess.py:92} INFO -   File "/opt/***/dags//extract.py", line 30, in extract
[2025-01-14T04:20:05.824+0000] {subprocess.py:92} INFO -     spark = SparkSession.builder.getOrCreate()
[2025-01-14T04:20:05.824+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/sql/session.py", line 228, in getOrCreate
[2025-01-14T04:20:05.825+0000] {subprocess.py:92} INFO -     sc = SparkContext.getOrCreate(sparkConf)
[2025-01-14T04:20:05.825+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/context.py", line 384, in getOrCreate
[2025-01-14T04:20:05.825+0000] {subprocess.py:92} INFO -     SparkContext(conf=conf or SparkConf())
[2025-01-14T04:20:05.825+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/context.py", line 144, in __init__
[2025-01-14T04:20:05.825+0000] {subprocess.py:92} INFO -     SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
[2025-01-14T04:20:05.825+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/context.py", line 331, in _ensure_initialized
[2025-01-14T04:20:05.826+0000] {subprocess.py:92} INFO -     SparkContext._gateway = gateway or launch_gateway(conf)
[2025-01-14T04:20:05.826+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/java_gateway.py", line 108, in launch_gateway
[2025-01-14T04:20:05.826+0000] {subprocess.py:92} INFO -     raise Exception("Java gateway process exited before sending its port number")
[2025-01-14T04:20:05.826+0000] {subprocess.py:92} INFO - Exception: Java gateway process exited before sending its port number
[2025-01-14T04:20:05.846+0000] {subprocess.py:96} INFO - Command exited with return code 1
[2025-01-14T04:20:05.856+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-14T04:20:05.859+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_influencer_marchendise, task_id=data_extract, execution_date=20250114T040134, start_date=20250114T042005, end_date=20250114T042005
[2025-01-14T04:20:05.866+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 8 for task data_extract (Bash command failed. The command returned a non-zero exit code 1.; 843)
[2025-01-14T04:20:05.901+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-01-14T04:20:05.919+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
