[2025-01-14T04:34:22.350+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ETL_influencer_marchendise.data_extract manual__2025-01-14T04:01:34.458324+00:00 [queued]>
[2025-01-14T04:34:22.355+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ETL_influencer_marchendise.data_extract manual__2025-01-14T04:01:34.458324+00:00 [queued]>
[2025-01-14T04:34:22.355+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-01-14T04:34:22.355+0000] {taskinstance.py:1369} INFO - Starting attempt 10 of 11
[2025-01-14T04:34:22.355+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-01-14T04:34:22.361+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): data_extract> on 2025-01-14 04:01:34.458324+00:00
[2025-01-14T04:34:22.364+0000] {standard_task_runner.py:52} INFO - Started process 1480 to run task
[2025-01-14T04:34:22.366+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_influencer_marchendise', 'data_extract', 'manual__2025-01-14T04:01:34.458324+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/AirflowM3.py', '--cfg-path', '/tmp/tmp3pjifaku', '--error-file', '/tmp/tmp6ka3zpf3']
[2025-01-14T04:34:22.367+0000] {standard_task_runner.py:80} INFO - Job 11: Subtask data_extract
[2025-01-14T04:34:22.401+0000] {task_command.py:371} INFO - Running <TaskInstance: ETL_influencer_marchendise.data_extract manual__2025-01-14T04:01:34.458324+00:00 [running]> on host b11c54afad7a
[2025-01-14T04:34:22.435+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=afif
AIRFLOW_CTX_DAG_ID=ETL_influencer_marchendise
AIRFLOW_CTX_TASK_ID=data_extract
AIRFLOW_CTX_EXECUTION_DATE=2025-01-14T04:01:34.458324+00:00
AIRFLOW_CTX_TRY_NUMBER=10
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-01-14T04:01:34.458324+00:00
[2025-01-14T04:34:22.436+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-01-14T04:34:22.437+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'sudo -u *** python /opt/***/dags/extract.py']
[2025-01-14T04:34:22.442+0000] {subprocess.py:85} INFO - Output:
[2025-01-14T04:34:23.131+0000] {subprocess.py:92} INFO - WARNING: An illegal reflective access operation has occurred
[2025-01-14T04:34:23.131+0000] {subprocess.py:92} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.7/site-packages/pyspark/jars/spark-unsafe_2.12-3.1.2.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2025-01-14T04:34:23.131+0000] {subprocess.py:92} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2025-01-14T04:34:23.131+0000] {subprocess.py:92} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2025-01-14T04:34:23.131+0000] {subprocess.py:92} INFO - WARNING: All illegal access operations will be denied in a future release
[2025-01-14T04:34:23.302+0000] {subprocess.py:92} INFO - 25/01/14 04:34:23 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-01-14T04:34:23.377+0000] {subprocess.py:92} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2025-01-14T04:34:23.377+0000] {subprocess.py:92} INFO - Setting default log level to "WARN".
[2025-01-14T04:34:23.377+0000] {subprocess.py:92} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-01-14T04:34:24.532+0000] {subprocess.py:92} INFO - Traceback (most recent call last):
[2025-01-14T04:34:24.533+0000] {subprocess.py:92} INFO -   File "/opt/***/dags/extract.py", line 42, in <module>
[2025-01-14T04:34:24.534+0000] {subprocess.py:92} INFO -     extract(path)
[2025-01-14T04:34:24.534+0000] {subprocess.py:92} INFO -   File "/opt/***/dags/extract.py", line 33, in extract
[2025-01-14T04:34:24.534+0000] {subprocess.py:92} INFO -     data = spark.read.csv(path, header=True, inferSchema=True)
[2025-01-14T04:34:24.534+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/sql/readwriter.py", line 737, in csv
[2025-01-14T04:34:24.534+0000] {subprocess.py:92} INFO -     return self._df(self._jreader.csv(self._spark._sc._jvm.PythonUtils.toSeq(path)))
[2025-01-14T04:34:24.534+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1305, in __call__
[2025-01-14T04:34:24.535+0000] {subprocess.py:92} INFO -     answer, self.gateway_client, self.target_id, self.name)
[2025-01-14T04:34:24.535+0000] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/sql/utils.py", line 117, in deco
[2025-01-14T04:34:24.535+0000] {subprocess.py:92} INFO -     raise converted from None
[2025-01-14T04:34:24.535+0000] {subprocess.py:92} INFO - pyspark.sql.utils.AnalysisException: Path does not exist: file:/opt/***/dagsmerch_sales.csv
[2025-01-14T04:34:24.987+0000] {subprocess.py:96} INFO - Command exited with return code 1
[2025-01-14T04:34:25.022+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-14T04:34:25.029+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_influencer_marchendise, task_id=data_extract, execution_date=20250114T040134, start_date=20250114T043422, end_date=20250114T043425
[2025-01-14T04:34:25.045+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 11 for task data_extract (Bash command failed. The command returned a non-zero exit code 1.; 1480)
[2025-01-14T04:34:25.067+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-01-14T04:34:25.086+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
