[2025-01-14T04:23:59.205+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ETL_influencer_marchendise.data_extract manual__2025-01-14T04:01:34.458324+00:00 [queued]>
[2025-01-14T04:23:59.210+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ETL_influencer_marchendise.data_extract manual__2025-01-14T04:01:34.458324+00:00 [queued]>
[2025-01-14T04:23:59.210+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-01-14T04:23:59.210+0000] {taskinstance.py:1369} INFO - Starting attempt 8 of 9
[2025-01-14T04:23:59.210+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-01-14T04:23:59.216+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): data_extract> on 2025-01-14 04:01:34.458324+00:00
[2025-01-14T04:23:59.219+0000] {standard_task_runner.py:52} INFO - Started process 985 to run task
[2025-01-14T04:23:59.221+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_influencer_marchendise', 'data_extract', 'manual__2025-01-14T04:01:34.458324+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/AirflowM3.py', '--cfg-path', '/tmp/tmpqaljjsap', '--error-file', '/tmp/tmp4t_b7cz_']
[2025-01-14T04:23:59.221+0000] {standard_task_runner.py:80} INFO - Job 9: Subtask data_extract
[2025-01-14T04:23:59.255+0000] {task_command.py:371} INFO - Running <TaskInstance: ETL_influencer_marchendise.data_extract manual__2025-01-14T04:01:34.458324+00:00 [running]> on host b11c54afad7a
[2025-01-14T04:23:59.299+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=afif
AIRFLOW_CTX_DAG_ID=ETL_influencer_marchendise
AIRFLOW_CTX_TASK_ID=data_extract
AIRFLOW_CTX_EXECUTION_DATE=2025-01-14T04:01:34.458324+00:00
AIRFLOW_CTX_TRY_NUMBER=8
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-01-14T04:01:34.458324+00:00
[2025-01-14T04:23:59.300+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-01-14T04:23:59.300+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/extract.py']
[2025-01-14T04:23:59.305+0000] {subprocess.py:85} INFO - Output:
[2025-01-14T04:23:59.398+0000] {subprocess.py:92} INFO - Traceback (most recent call last):
[2025-01-14T04:23:59.399+0000] {subprocess.py:92} INFO -   File "/opt/***/dags/extract.py", line 41, in <module>
[2025-01-14T04:23:59.399+0000] {subprocess.py:92} INFO -     extract(path)
[2025-01-14T04:23:59.399+0000] {subprocess.py:92} INFO - NameError: name 'path' is not defined
[2025-01-14T04:23:59.410+0000] {subprocess.py:96} INFO - Command exited with return code 1
[2025-01-14T04:23:59.418+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-14T04:23:59.420+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_influencer_marchendise, task_id=data_extract, execution_date=20250114T040134, start_date=20250114T042359, end_date=20250114T042359
[2025-01-14T04:23:59.426+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 9 for task data_extract (Bash command failed. The command returned a non-zero exit code 1.; 985)
[2025-01-14T04:23:59.444+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-01-14T04:23:59.461+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
